import { defineField, defineType } from "sanity";

export const postType = defineType({
  name: "post",
  title: "Insight Article",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      title: "URL Slug",
      description: "Becomes the article URL: /insights/your-slug",
      group: "content",
      options: { source: "title" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      type: "string",
      title: "Category",
      description: "e.g. AI Search, Semantic SEO, Local SEO, Entity SEO",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "readTime",
      type: "string",
      title: "Read Time",
      description: "e.g. 6 min read",
      group: "content",
    }),
    defineField({
      name: "publishedDate",
      type: "date",
      title: "Published Date",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "summary",
      type: "text",
      title: "Summary",
      description: "One or two sentence teaser shown on the Insights list page",
      rows: 3,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "featuredImage",
      type: "image",
      title: "Featured Image",
      description: "Shown at the top of the article and used as the social share preview image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          type: "string",
          title: "Alt Text",
          description: "Describe the image for accessibility and SEO — required if an image is set",
        }),
      ],
    }),
    defineField({
      name: "contentMarkdown",
      type: "text",
      title: "Article Body (Markdown)",
      description:
        "Use ## for headings, ### for subheadings, **bold** for emphasis, - for bullet lists. To insert an image inline, use: ![alt text](image-url). To insert a table, use standard markdown table syntax with | pipes and a header divider row.",
      rows: 20,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "metaTitle",
      type: "string",
      title: "SEO Title",
      description: "Overrides the page <title> tag for search engines. Leave blank to use the article Title above. Keep under 60 characters.",
      group: "seo",
      validation: (rule) => rule.max(60).warning("Longer titles may get truncated in search results"),
    }),
    defineField({
      name: "metaDescription",
      type: "text",
      title: "Meta Description",
      description: "The snippet shown under your link in Google search results. Leave blank to use the Summary above. Keep under 160 characters.",
      rows: 2,
      group: "seo",
      validation: (rule) => rule.max(160).warning("Longer descriptions get truncated in search results"),
    }),
    defineField({
      name: "canonicalUrl",
      type: "url",
      title: "Canonical URL (optional)",
      description: "Only needed if this content is republished elsewhere and you want to point search engines to the original source.",
      group: "seo",
    }),
    defineField({
      name: "noIndex",
      type: "boolean",
      title: "Hide from search engines",
      description: "Turn on to prevent this article from being indexed by Google (e.g. for drafts you've published but aren't ready to promote)",
      group: "seo",
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "category",
      media: "featuredImage",
    },
  },
});
